### ISSUE TITLE
Watches key in config_hash should expect an array of hashes?

### ISSUE THREAD

**Issue by miroswan** [solarkennedy/puppet-consul#83] opened 2015-02-18 20:05 UTC
Hey, so. Looking at the consul configuration syntax, it looks like the watches value should be an array of hashes. Each watcher is a hash and indexed in an array. I'm not sure how to configure my watches using this puppet module since the watches key in the configuration hash is expecting a hash value instead of an array value. If this is by design, would you mind briefly explaining how to configure this key properly? Otherwise, this is probably a bug. 

Thanks.

**Comment by solarkennedy** [comment] 2015-02-19 03:37
According to the tests it is a hash:
https://github.com/solarkennedy/puppet-consul/blob/master/spec/classes/init_spec.rb#L247

It looks like the default is an empty hash and we are validating that it is as hash:
https://github.com/solarkennedy/puppet-consul/blob/master/manifests/init.pp#L62-L73

But it looks like we lack docs on this. Can you make a PR that adds a docstring in the init.pp and maybe and example in README.md?

Being a hash you would configure it like this:

```puppet
class { consul:
  ...
  watches => {
    'haproxy' => {
      'key'     => 'services/haproxy/',
      'handler' => 'rebuild_haproxy.sh',
    }
    'sshd' => {
      'key'     => 'services/sshd',
      'handler' => 'rebuild_sshd.sh',
    }
  }
  services => {}
  checks => {}
}
```

Or in hiera it would be in yaml form.

**Comment by miroswan** [comment] 2015-02-23 19:17
This causes a dependency loop:

```puppet
class { 'consul':
  config_hash => {
    'data_dir'   => '/cust/consul',     
    'datacenter' => 'devint',
    'log_level'  => 'INFO',
    'node_name'  => "${fqdn}"
  },
  watches     => {
    'services'       => {
      'type'    => 'services',
      'handler' => 'sudo python /usr/local/bin/reacktor services'
    },
    'httpd_service'  => {
      'type'    => 'service',
      'service' => 'httpd',
      'handler' => 'sudo python /usr/local/bin/reacktor service --service httpd'
    },
    'tomcat_service' => {
      'type'    => 'service',
      'service' => 'tomcat',
        'handler' => 'sudo python /usr/local/bin/reacktor service --service tomcat'
    }
  }
}
```

err: Could not apply complete catalog: Found 1 dependency cycle:
(File[/etc/consul/watch_httpd_service.json] => Class[Consul::Run_service] => Service[consul] => Class[Consul::Run_service] => Class[Consul] => Consul::Watch[httpd_service] => File[/etc/consul/watch_httpd_service.json])

**Comment by solarkennedy** [comment] 2015-02-24 05:09
I'm having trouble reproducing your issue. 

So I've added a test case with exactly the input you provided. 
https://github.com/solarkennedy/puppet-consul/blob/master/spec/classes/init_spec.rb#L287

Here are the test results:
https://travis-ci.org/solarkennedy/puppet-consul/builds/51933146

**Comment by solarkennedy** [comment] 2015-02-25 03:43
@miroswan  can you confirm you are running the latest version of the code?

**Comment by miroswan** [comment] 2015-02-25 05:24
I'm running v0.4.6. I ended up overriding the config.json resource and templating it so I can avoid the aforementioned issue and gain a bit more more flexibility. Aside from the watches key in the config_hash class param, the consul module has been working out just fine for me. If the tests are passing, I suppose it's fine to mark this one as closed for now. Possible PEBCAK on my end.

**Comment by solarkennedy** [comment] 2015-02-25 15:36
Possibly. Can you try the tip of master and confirm that whatever bug that you are hitting is fixed? That way we can close this issue with confidence.

**Comment by aj-jester** [comment] 2015-07-17 04:00
@miroswan Your dependency issue (whether it was really an issue or not) might be fixed with this PR https://github.com/solarkennedy/puppet-consul/pull/152

Can you pull down the latest master and try it again?

**Comment by split3** [comment] 2016-03-25 13:31
Closing as this is an old issue and seems to be fixed.  If not please re-open the issue.

**Closed by split3** 2016-03-25 13:31 UTC
